//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оборудование
    {
        public int Id { get; set; }
        public string Наименование_борудования { get; set; }
        public string Тип { get; set; }
        public string Серийный_номер { get; set; }
        public string MAC_Адрес { get; set; }
        public string IP_Адрес { get; set; }
        public string Список_телефонов { get; set; }
        public Nullable<System.DateTime> Дата_устоновки { get; set; }
    }
}
