//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class Подключения
    {
        public int Id { get; set; }
        public int Пользователь { get; set; }
        public string Тарифный_план { get; set; }
        public string Оборудование { get; set; }
        public string Адрес_установки { get; set; }
        public string Место_устоновки { get; set; }
        public string Телефон { get; set; }
        public string Точка_подключения { get; set; }
    }
}
